replicaCount: 1

image:
  repository: ghcr.io/${{ values.destination.owner }}/${{ values.name }}
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

metrics:
  enabled: true
  path: /metrics
  port: 8080
